// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYj0-MxfwCUr0H9ZIR-wpoO6freDUtKK4',
    appId: '1:760737053618:web:d7bbb88151f70c7504c2ab',
    messagingSenderId: '760737053618',
    projectId: 'push-notification-exampl-a3640',
    authDomain: 'push-notification-exampl-a3640.firebaseapp.com',
    storageBucket: 'push-notification-exampl-a3640.appspot.com',
    measurementId: 'G-WNP67VGD37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6J47nG7KQCc8xjfnkQNKnqy-xKWkkMuU',
    appId: '1:760737053618:android:f358a72c93c85c6a04c2ab',
    messagingSenderId: '760737053618',
    projectId: 'push-notification-exampl-a3640',
    storageBucket: 'push-notification-exampl-a3640.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXyQAIyQ0T5-0F71347TGS5lblCb2-oSw',
    appId: '1:760737053618:ios:ba2a0585ed9d127d04c2ab',
    messagingSenderId: '760737053618',
    projectId: 'push-notification-exampl-a3640',
    storageBucket: 'push-notification-exampl-a3640.appspot.com',
    iosBundleId: 'com.example.pushNotificationExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXyQAIyQ0T5-0F71347TGS5lblCb2-oSw',
    appId: '1:760737053618:ios:ba4ca20617f78bdb04c2ab',
    messagingSenderId: '760737053618',
    projectId: 'push-notification-exampl-a3640',
    storageBucket: 'push-notification-exampl-a3640.appspot.com',
    iosBundleId: 'com.example.pushNotificationExample.RunnerTests',
  );
}
